# Generated by Django 3.1.4 on 2020-12-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='about',
            field=models.TextField(default='no content', max_length=1044, verbose_name='hero discribtion'),
        ),
    ]
