# Generated by Django 3.1.4 on 2021-01-14 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(default='Alt', max_length=256)),
                ('source', models.ImageField(blank=True, null=True, upload_to='hero/')),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='image',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='RestApi.image', verbose_name="Hero's picture"),
        ),
    ]
