# Generated by Django 3.1.4 on 2020-12-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0002_world_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
