# Generated by Django 3.1.4 on 2021-01-16 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=255, verbose_name='category name')),
                ('has_subcategory', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=255, verbose_name='category name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Product', max_length=256, verbose_name='name')),
                ('barcode', models.IntegerField(default=0, verbose_name='barcode')),
                ('slug', models.SlugField(default=None, editable=False, max_length=255)),
                ('category', models.ManyToManyField(to='CascadeCat.Category', verbose_name='Category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CascadeCat.subcategory', verbose_name='sub category'),
        ),
    ]
