# Generated by Django 3.1.4 on 2021-01-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CascadeCat', '0004_auto_20210121_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='null', max_length=255, verbose_name="sub category 's' name"),
        ),
    ]
